### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by jinrenfit** [MitchellChu/torndsession#18]
packages/torndsession/memorysession.py", line 63, in save
    self.remove_expires()
  File "/home/cco/venv/lib/python2.7/site-packages/torndsession/memorysession.py", line 73, in remove_expires
    for key, val in iteritems(self._data_handler):
RuntimeError: dictionary changed size during iteration

**Comment by HQ1363** [comment]
笑了，我也遇到了，正想提PR，但是有人已经提过了。但是为啥还不合呀，算了，二开打包吧
