### ISSUE TITLE
How to delete session?

### ISSUE THREAD

**Issue by moasakthi** [MitchellChu/torndsession#4]
Hi, 

First of all thank you for wonderful session library.

And my issue is , i cannot able delete session .
del self.session['user_name']

i getting an error.
 del self.session['user_name']
AttributeError: **delitem**

can you please help me out..

**Comment by MitchellChu** [comment]
delete session data:

``` python
self.session.delete("key")
```

self.session is not a dictionary object in context.

**Comment by moasakthi** [comment]
Thank you. works fine
