### ISSUE TITLE
关于session过期时间

### ISSUE THREAD

**Issue by phith0n** [MitchellChu/torndsession#5]
session过期时间的起始时间好像是以设置的时候为准的，而不是以最后一次操作的时间为准的，感觉不太好。如果我一直在操作，突然提交一个表单的时候过期了，很多东西就悲剧了。
我没有具体看你的代码，不过好像是这样的。

**Comment by MitchellChu** [comment]
By default：session is sliding expiration. Session timeout = 20 minutes.

你可以利用expires和expires_days来自定义过期时间。
1. expires 使用的是绝对过期时间(absolute expiration)
2. expires_days是滑动过期时间(sliding expiration)
